In [1]:
# temp = ncfile.variables[Y]
# y_data = temp[:]*1
# print(y_data, y_data.shape)
# plt.figure()
# plt.hist(y_data)

# temp = ncfile.variables[X]
# x_data = temp[:]*1
# print(x_data, x_data.shape)
# plt.figure()
# plt.hist(x_data)


In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame as df

import datetime
from datetime import datetime as dt
import matplotlib.pyplot as plt

import os
from scipy.io import netcdf
import netCDF4
import rioxarray

In [312]:
print(os.getcwd())
DATA_FOLDER = '/Users/vbc5136/Documents/Acads/3-Fall23/RA:Thesis/_SRA-2023/_Data/'
RESULTS_FOLDER = '/Users/vbc5136/Documents/Acads/3-Fall23/RA:Thesis/_SRA-2023/_Results/'
CODE_FOLDER = '/Users/vbc5136/Documents/Acads/3-Fall23/RA:Thesis/_SRA-2023/_Code/'

NARR_DATA_FOLDER = DATA_FOLDER + 'NARR/'
files = os.listdir(NARR_DATA_FOLDER)
files

/Users/vbc5136/Documents/Acads/3-Fall23/RA:Thesis/_SRA-2023/_Code


['qvflux.2018.nc', '.DS_Store', 'air.sfc.2018.nc', 'air.2m.2019.nc']

In [313]:
for file in [files[3]]:
#     ncfile = netcdf.NetCDFFile(NARR_DATA_FOLDER + file,'r')
    DATA_STORAGE_FILENAME = file.split('.nc')[0]
    ncfile = netCDF4.Dataset(NARR_DATA_FOLDER + file)
#     temp = ncfile.variables[var] # var can be 'Theta', 'S', 'V', 'U' etc..
#     data = temp[:]*1
#     file2read.close()
print(ncfile.variables.keys())
print(ncfile.variables)
ncfile


dict_keys(['time', 'lat', 'lon', 'y', 'x', 'Lambert_Conformal', 'air', 'time_bnds'])
{'time': <class 'netCDF4._netCDF4.Variable'>
float64 time(time)
    axis: T
    long_name: Time
    standard_name: time
    units: hours since 1800-1-1 00:00:0.0
    delta_t: 0000-00-01 00:00:00
    avg_period: 0000-00-01 00:00:00
    actual_range: [1919712. 1928448.]
    coordinate_defines: start
unlimited dimensions: time
current shape = (365,)
filling on, default _FillValue of 9.969209968386869e+36 used, 'lat': <class 'netCDF4._netCDF4.Variable'>
float32 lat(y, x)
    axis: Y
    coordinate_defines: point
    long_name: Latitude
    standard_name: latitude
    units: degrees_north
unlimited dimensions: 
current shape = (277, 349)
filling on, default _FillValue of 9.969209968386869e+36 used, 'lon': <class 'netCDF4._netCDF4.Variable'>
float32 lon(y, x)
    axis: X
    coordinate_defines: point
    long_name: Longitude
    standard_name: longitude
    units: degrees_east
unlimited dimensions: 
current 

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4_CLASSIC data model, file format HDF5):
    Conventions: CF-1.2
    centerlat: 50.0
    centerlon: -107.0
    comments: 
    institution: National Centers for Environmental Prediction
    latcorners: [ 1.000001  0.897945 46.3544   46.63433 ]
    loncorners: [-145.5       -68.32005    -2.569891  148.6418  ]
    platform: Model
    standardpar1: 50.0
    standardpar2: 50.000001
    title: Daily NARR
    history: created Sat Mar 26 04:54:47 MDT 2016 by NOAA/ESRL/PSD
    dataset_title: NCEP North American Regional Reanalysis (NARR)
    references: https://www.esrl.noaa.gov/psd/data/gridded/data.narr.html
    source: http://www.emc.ncep.noaa.gov/mmb/rreanl/index.html
    References: 
    dimensions(sizes): time(365), y(277), x(349), nbnds(2)
    variables(dimensions): float64 time(time), float32 lat(y, x), float32 lon(y, x), float32 y(y), float32 x(x), int32 Lambert_Conformal(), float32 air(time, y, x), float64 time_bnds(time, nbnds)
   

In [314]:
time_date_data = [REF_DATE + datetime.timedelta(hours=ts) for ts in time_data]
time_date_data

[datetime.datetime(2019, 1, 1, 0, 0),
 datetime.datetime(2019, 1, 2, 0, 0),
 datetime.datetime(2019, 1, 3, 0, 0),
 datetime.datetime(2019, 1, 4, 0, 0),
 datetime.datetime(2019, 1, 5, 0, 0),
 datetime.datetime(2019, 1, 6, 0, 0),
 datetime.datetime(2019, 1, 7, 0, 0),
 datetime.datetime(2019, 1, 8, 0, 0),
 datetime.datetime(2019, 1, 9, 0, 0),
 datetime.datetime(2019, 1, 10, 0, 0),
 datetime.datetime(2019, 1, 11, 0, 0),
 datetime.datetime(2019, 1, 12, 0, 0),
 datetime.datetime(2019, 1, 13, 0, 0),
 datetime.datetime(2019, 1, 14, 0, 0),
 datetime.datetime(2019, 1, 15, 0, 0),
 datetime.datetime(2019, 1, 16, 0, 0),
 datetime.datetime(2019, 1, 17, 0, 0),
 datetime.datetime(2019, 1, 18, 0, 0),
 datetime.datetime(2019, 1, 19, 0, 0),
 datetime.datetime(2019, 1, 20, 0, 0),
 datetime.datetime(2019, 1, 21, 0, 0),
 datetime.datetime(2019, 1, 22, 0, 0),
 datetime.datetime(2019, 1, 23, 0, 0),
 datetime.datetime(2019, 1, 24, 0, 0),
 datetime.datetime(2019, 1, 25, 0, 0),
 datetime.datetime(2019, 1, 26, 0,

In [315]:
LATITUDE = 'lat'
LONGITUDE = 'lon'
TIME = 'time'
Y = 'y'
X = 'x'
LC = 'Lambert_Conformal'
AIR = 'air'
TIME_BNDS = 'time_bnds'

REF_DATE = dt(1800, 1, 1, 0, 0, 0)

In [316]:
temp = ncfile.variables[AIR]
air_data = temp[:]*1
print(AIR, air_data, air_data.shape)
air_data_stack = np.concatenate(air_data, axis=None)
print(air_data_stack.shape)


air [[[298.4115295410156 298.2240295410156 298.2240295410156 ... -- -- --]
  [298.3724670410156 298.3724670410156 298.1224670410156 ... -- -- --]
  [298.4193420410156 298.3099670410156 298.3099670410156 ... -- -- --]
  ...
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]]

 [[299.50244140625 299.47900390625 299.47900390625 ... -- -- --]
  [299.43994140625 299.43994140625 299.39306640625 ... -- -- --]
  [299.42431640625 299.35400390625 299.35400390625 ... -- -- --]
  ...
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]]

 [[299.0908508300781 298.9580383300781 298.9580383300781 ... -- -- --]
  [299.0439758300781 299.0439758300781 298.8799133300781 ... -- -- --]
  [299.1455383300781 298.9892883300781 298.9892883300781 ... -- -- --]
  ...
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]
  [-- -- -- ... -- -- --]]

 ...

 [[299.13165283203125 299.13946533203125 299.13946533203125 ... -- -- --]
  [299.16290283203125 299.16290283203

In [317]:
temp = ncfile.variables[TIME]
time_data = temp[:]*1
time_date_data = [REF_DATE + datetime.timedelta(hours=ts) for ts in time_data]
time_date_data = [date_time.date() for date_time in time_date_data]
print(TIME, time_data, time_data.shape, time_date_data, len(time_date_data))


time [1919712. 1919736. 1919760. 1919784. 1919808. 1919832. 1919856. 1919880.
 1919904. 1919928. 1919952. 1919976. 1920000. 1920024. 1920048. 1920072.
 1920096. 1920120. 1920144. 1920168. 1920192. 1920216. 1920240. 1920264.
 1920288. 1920312. 1920336. 1920360. 1920384. 1920408. 1920432. 1920456.
 1920480. 1920504. 1920528. 1920552. 1920576. 1920600. 1920624. 1920648.
 1920672. 1920696. 1920720. 1920744. 1920768. 1920792. 1920816. 1920840.
 1920864. 1920888. 1920912. 1920936. 1920960. 1920984. 1921008. 1921032.
 1921056. 1921080. 1921104. 1921128. 1921152. 1921176. 1921200. 1921224.
 1921248. 1921272. 1921296. 1921320. 1921344. 1921368. 1921392. 1921416.
 1921440. 1921464. 1921488. 1921512. 1921536. 1921560. 1921584. 1921608.
 1921632. 1921656. 1921680. 1921704. 1921728. 1921752. 1921776. 1921800.
 1921824. 1921848. 1921872. 1921896. 1921920. 1921944. 1921968. 1921992.
 1922016. 1922040. 1922064. 1922088. 1922112. 1922136. 1922160. 1922184.
 1922208. 1922232. 1922256. 1922280. 1922304. 

In [318]:
temp = ncfile.variables[LATITUDE]
lat_data = temp[:]*1
temp = ncfile.variables[LONGITUDE]
lon_data = temp[:]*1

print(LATITUDE, lat_data, lat_data.shape)
print(LONGITUDE, lon_data, lon_data.shape)

# ncfile.variables[LATITUDE], ncfile.variables[LONGITUDE]

lat [[ 1.000001  1.104305  1.208292 ...  1.106851  1.002554  0.897945]
 [ 1.184838  1.289653  1.39415  ...  1.292212  1.187404  1.082283]
 [ 1.369977  1.475305  1.580315 ...  1.477877  1.372555  1.266921]
 ...
 [46.52934  46.8157   47.10208  ... 46.8227   46.53634  46.25001 ]
 [46.58263  46.8693   47.156    ... 46.87632  46.58964  46.303   ]
 [46.63433  46.9213   47.20831  ... 46.92832  46.64134  46.3544  ]] (277, 349)
lon [[-145.5      -145.315    -145.1295   ...  -68.68951   -68.50452
   -68.32005 ]
 [-145.6047   -145.4194   -145.2336   ...  -68.58509   -68.39979
   -68.215   ]
 [-145.71     -145.5244   -145.3383   ...  -68.48015   -68.29454
   -68.10945 ]
 ...
 [ 149.476     149.555     149.6349   ...   -3.556949   -3.477873
    -3.399673]
 [ 149.0593    149.1361    149.2138   ...   -3.137999   -3.061175
    -2.985206]
 [ 148.6418    148.7163    148.7917   ...   -2.718174   -2.643617
    -2.569891]] (277, 349)


In [319]:
print(np.min(lat_data), np.max(lat_data), np.min(lon_data), np.max(lon_data))

# plt.figure()
# plt.hist(lat_data)
# plt.figure()
# plt.hist(lon_data)
# plt.figure()
# plt.plot(lon_data, lat_data)

0.897945 85.33255 -179.9969 179.9928


#### Concatenate/Stack the 2d 3d arrays into 1d arrays for dataframe cols

In [320]:
master_df = df({LATITUDE:[], LONGITUDE: [], TIME: [], AIR: []})
master_df

Empty DataFrame
Columns: [lat, lon, time, air]
Index: []

In [321]:
lat_data_stack = np.concatenate(lat_data, axis=None)
lon_data_stack = np.concatenate(lon_data, axis=None)
print(lat_data_stack[0:10])
print(lon_data_stack[0:10])
print(lat_data_stack.shape)

lat_data_stack = np.round(lat_data_stack, 2)
lon_data_stack = np.round(lon_data_stack, 2)
print(lat_data_stack[100:110])
print(lon_data_stack[100:110])
print(lat_data_stack.shape)


[1.000001 1.104305 1.208292 1.311956 1.415297 1.51831  1.62099  1.723334
 1.825337 1.926998]
[-145.5    -145.315  -145.1295 -144.9435 -144.757  -144.57   -144.3824
 -144.1943 -144.0058 -143.8167]
(96673,)
[9.25 9.31 9.36 9.41 9.46 9.52 9.57 9.62 9.67 9.71]
[-124.59 -124.36 -124.13 -123.9  -123.67 -123.43 -123.2  -122.97 -122.74
 -122.5 ]
(96673,)


In [322]:
# temp_df.to_excel(
#     DATA_STORAGE_FILENAME + '.' + str(day.month) + '.' + str(day.day) + '.xlsx', index=False)

In [323]:
for day, air_daily in zip(time_date_data, air_data):
    air_daily_stack = np.concatenate(air_daily, axis=None)
    day_series = pd.Series(day, air_daily_stack)
#     print(len(lat_data_stack), len(lon_data_stack), len(air_daily_stack), len(day_series))
    temp_df = df({LATITUDE: lat_data_stack,
                  LONGITUDE: lon_data_stack,
                  TIME: day_series, AIR: air_daily_stack})
    print(temp_df.shape)
    temp_df.to_excel(
        DATA_STORAGE_FILENAME + '.' + str(day.month) + '.' + str(day.day) + '.xlsx',
        index=False)
#     master_df = master_df.append(temp_df)
# master_df.shape

(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)
(96673, 4)


KeyboardInterrupt: 

In [288]:
# master_df.to_excel('air2m_2019.xlsx')
print(master_df.shape)
master_df


(35285645, 4)


lat         lon        time           air
 2.984115e+02   1.000000 -145.500000  2019-01-01  2.984115e+02
 2.982240e+02   1.100000 -145.320007  2019-01-01  2.982240e+02
 2.982240e+02   1.210000 -145.130005  2019-01-01  2.982240e+02
 2.979584e+02   1.310000 -144.940002  2019-01-01  2.979584e+02
 2.977475e+02   1.420000 -144.759995  2019-01-01  2.977475e+02
...                  ...         ...         ...           ...
-9.969210e+36  47.500000   -2.870000  2019-12-31 -9.969210e+36
-9.969210e+36  47.220001   -2.790000  2019-12-31 -9.969210e+36
-9.969210e+36  46.930000   -2.720000  2019-12-31 -9.969210e+36
-9.969210e+36  46.639999   -2.640000  2019-12-31 -9.969210e+36
-9.969210e+36  46.349998   -2.570000  2019-12-31 -9.969210e+36

[35285645 rows x 4 columns]

In [289]:
master_df.groupby([LATITUDE, LONGITUDE, TIME]).mean()

air
lat       lon         time                    
0.900000  -68.320000  2019-01-01 -9.969210e+36
                      2019-01-02 -9.969210e+36
                      2019-01-03 -9.969210e+36
                      2019-01-04 -9.969210e+36
                      2019-01-05 -9.969210e+36
...                                        ...
85.330002 -103.389999 2019-12-27  2.467259e+02
                      2019-12-28  2.489144e+02
                      2019-12-29  2.477801e+02
                      2019-12-30  2.450506e+02
                      2019-12-31  2.416947e+02

[35285645 rows x 1 columns]

In [290]:
np.unique(master_df[LATITUDE]).shape, master_df[LATITUDE].shape

((8229,), (35285645,))

In [291]:
np.unique(master_df[LONGITUDE]).shape, master_df[LONGITUDE].shape

((19240,), (35285645,))

In [275]:
master_df[LATITUDE].tolist()

[1.0,
 1.100000023841858,
 1.2100000381469727,
 1.309999942779541,
 1.4199999570846558,
 1.5199999809265137,
 1.6200000047683716,
 1.7200000286102295,
 1.8300000429153442,
 1.9299999475479126,
 2.0299999713897705,
 2.130000114440918,
 2.2300000190734863,
 2.3299999237060547,
 2.430000066757202,
 2.5299999713897705,
 2.630000114440918,
 2.7300000190734863,
 2.8299999237060547,
 2.9200000762939453,
 3.0199999809265137,
 3.119999885559082,
 3.2200000286102295,
 3.309999942779541,
 3.4100000858306885,
 3.5,
 3.5999999046325684,
 3.690000057220459,
 3.7899999618530273,
 3.880000114440918,
 3.9800000190734863,
 4.070000171661377,
 4.159999847412109,
 4.25,
 4.349999904632568,
 4.440000057220459,
 4.53000020980835,
 4.619999885559082,
 4.710000038146973,
 4.800000190734863,
 4.889999866485596,
 4.980000019073486,
 5.059999942779541,
 5.150000095367432,
 5.239999771118164,
 5.329999923706055,
 5.409999847412109,
 5.5,
 5.579999923706055,
 5.670000076293945,
 5.75,
 5.840000152587891,
 5.920000

#### Read plant_info list of plants (lat, lon)
#### filter master_df (lat, lon) using the unique entries of plants (lat, lon)
#### combine the plant (lat, lon) df with master_df (lat, lon) 

In [187]:
plant_lat_lon_df = pd.read_excel('lat_lon_df.xlsx')
plant_lat_lon_df

Plant Code   Latitude   Longitude    lat     lon
0              2  33.458665  -87.356823  33.46  -87.36
1              3    31.0069    -88.0103  31.01  -88.01
2              4  32.583889  -86.283056  32.58  -86.28
3              7    34.0128    -85.9708  34.01  -85.97
4              8  33.644344  -87.196486  33.64  -87.20
...          ...        ...         ...    ...     ...
6895       58540  32.713889 -108.248056  32.71 -108.25
6896       58541      43.79      -72.49  43.79  -72.49
6897       58542    33.8055   -115.3947  33.81 -115.39
6898       58543  33.355862 -111.802355  33.36 -111.80
6899       58544  36.390556 -114.964444  36.39 -114.96

[6900 rows x 5 columns]

In [182]:
plant_lat_lon_df['Latitude'][2]

32.583889

In [179]:
master_df[LATITUDE][master_df[LATITUDE] == plant_lat_lon_df['Latitude'][2]]

Series([], Name: lat, dtype: float32)

In [186]:
plant_lat_lon_df[LATITUDE][2] in master_df[LATITUDE].tolist()

False